### ISSUE TITLE
Paseo paraId reserve not working, reverting with error AlreadyRegistered

### ISSUE THREAD

**Issue by Cvijan4PointO** [paseo-network/paseo-chain-specs#4]
I have been trying to reserve a paraId, and it keeps reverting with the error that it is already registered.
![image](https://github.com/user-attachments/assets/df6fde5e-a348-4175-9cf1-6b7e5c5370cd)
Can someone look at this, I do not care for specific paraId, so if someone could help please get in touch with me.

**Comment by al3mart** [comment]
Hey @CvijanCBS, thanks for reaching out.

Some of the paraIds are force registered into the relay as we assist teams by keeping their paraIds if that makes sense for them.
I have bump now the next available paraId to remove the overlap. Now you can go ahead and reserve your id without problems.

If anything else is needed, please feel free to open an issue any time at https://github.com/paseo-network/support/issues rather than in this repo :)
